/**
 * Standard API envelope, pagination and correlation primitives.
 *
 * Source of truth: `docs/architecture/51-api-conventions.md` (envelope,
 * pagination, idempotency, concurrency) and
 * `docs/architecture/61-dto-contracts.md` (DTO rules).
 */
import { z } from 'zod';

import {
  ERROR_CODE_VALUES,
  type ErrorCode,
} from './errors';

/* -------------------------------------------------------------------------- */
/* Correlation identifiers                                                    */
/* -------------------------------------------------------------------------- */

declare const __brand: unique symbol;

/** Nominal brand helper for string-based identifiers. */
export type Brand<TValue, TBrand extends string> = TValue & {
  readonly [__brand]: TBrand;
};

/** Branded correlation id; generated by the platform, propagated end-to-end. */
export type CorrelationId = Brand<string, 'CorrelationId'>;

/**
 * Correlation ids are strict on output (platform generates UUIDs) but lenient
 * on input so foreign trace parents from gateways/clients are never dropped;
 * only empty or whitespace-only values are rejected.
 */
export const correlationIdSchema = z
  .string()
  .trim()
  .min(1)
  .max(128)
  .transform((value) => value as CorrelationId);

/** Generate a new correlation id (UUID v4). */
export function newCorrelationId(): CorrelationId {
  return globalThis.crypto.randomUUID() as CorrelationId;
}

/* -------------------------------------------------------------------------- */
/* Error envelope                                                             */
/* -------------------------------------------------------------------------- */

/**
 * Machine-readable error payload. Clients must branch on `code`; `message` is
 * for humans and may change without notice.
 */
export interface ApiError {
  code: ErrorCode;
  message: string;
  details?: Record<string, unknown>;
  correlationId?: string;
}

/** Standard error response body. */
export interface ApiErrorBody {
  error: ApiError;
}

const errorCodeSchema = z.enum(ERROR_CODE_VALUES);

export const apiErrorSchema = z.object({
  code: errorCodeSchema,
  message: z.string().min(1),
  details: z.record(z.string(), z.unknown()).optional(),
  correlationId: z.string().min(1).optional(),
});

export const apiErrorBodySchema = z.object({ error: apiErrorSchema });

/* -------------------------------------------------------------------------- */
/* Success envelope                                                           */
/* -------------------------------------------------------------------------- */

/** Single-resource success body. */
export interface ApiSuccess<TData> {
  data: TData;
}

/** Cursor page metadata as exposed on the wire (`51-api-conventions.md`). */
export interface PageInfo {
  /** Opaque cursor for the next page; `null` when the page is the last one. */
  nextCursor: string | null;
  hasMore: boolean;
}

/** List success body: items plus page metadata side by side. */
export interface ApiPaginatedSuccess<TItem> {
  data: TItem[];
  page: PageInfo;
}

/**
 * The full response-body union an API adapter emits:
 * `{ data }` / `{ data, page }` on success, `{ error }` on failure.
 * HTTP status decides which half applies; this union is for typed handlers.
 */
export type ApiEnvelope<TData> = ApiSuccess<TData> | ApiPaginatedSuccess<TData> | ApiErrorBody;

export function apiSuccessSchema<TData extends z.ZodType>(data: TData) {
  return z.object({ data });
}

export const pageInfoSchema = z.object({
  nextCursor: z.string().min(1).nullable(),
  hasMore: z.boolean(),
});

export function apiPaginatedSuccessSchema<TItem extends z.ZodType>(item: TItem) {
  return z.object({ data: z.array(item), page: pageInfoSchema });
}

/**
 * Parse any half of {@link ApiEnvelope}; useful at client boundaries. The
 * paginated variant is validated structurally (items as unknown); use
 * {@link apiPaginatedSuccessSchema} when item-level validation is required.
 */
export function apiEnvelopeSchema<TData extends z.ZodType>(data: TData) {
  return z.union([
    apiSuccessSchema(data),
    apiPaginatedSuccessSchema(z.unknown()),
    apiErrorBodySchema,
  ]);
}

/** Structural discriminator between error bodies and success envelopes. */
export function isApiErrorBody(value: unknown): value is ApiErrorBody {
  return (
    typeof value === 'object' &&
    value !== null &&
    'error' in value &&
    typeof (value as { error: unknown }).error === 'object' &&
    (value as { error: unknown }).error !== null
  );
}

/* -------------------------------------------------------------------------- */
/* Cursor pagination                                                          */
/* -------------------------------------------------------------------------- */

/** Inbound cursor pagination request (`?limit=50&after=<cursor>`). */
export interface CursorPageRequest {
  limit?: number;
  /**
   * Opaque continuation cursor taken from the previous page's
   * `page.nextCursor`. Wire/query name is `after` (51-api-conventions.md).
   */
  after?: string;
}

/**
 * Outbound cursor pagination result primitive used inside modules.
 * API adapters map it onto {@link ApiPaginatedSuccess}'s `page` field.
 */
export interface CursorPage<TItem> {
  items: TItem[];
  /**
   * Cursor to continue after the last returned item; `undefined` while a page
   * is still being assembled, `null` once known to be the last page.
   */
  nextCursor?: string | null;
  hasMore: boolean;
}

/**
 * Query-string friendly request schema: HTTP queries arrive as strings, so
 * `limit` is coerced. Default of 50 and max of 200 follow the convention doc's
 * example (`?limit=50`) with a defensive upper bound.
 */
export const cursorPageRequestSchema = z.object({
  limit: z.coerce.number().int().min(1).max(200).default(50),
  after: z.string().min(1).optional(),
});

/** Schema factory for {@link CursorPage}. */
export function cursorPageSchema<TItem extends z.ZodType>(item: TItem) {
  return z.object({
    items: z.array(item),
    nextCursor: z.string().min(1).nullable().optional(),
    hasMore: z.boolean(),
  });
}

/** Normalize a {@link CursorPage} into wire-level {@link PageInfo}. */
export function toPageInfo<TItem>(page: CursorPage<TItem>): PageInfo {
  return { nextCursor: page.nextCursor ?? null, hasMore: page.hasMore };
}
